In [2]:
import pandas as pd
import os


user = os.getlogin()
exportação = pd.read_csv(f'./ExpVinho.csv', sep=';')

df_transposto = exportação.melt(id_vars=['Id', 'País'], var_name='Ano', value_name='Valor')
df_transposto[['Ano', 'Tipo']] = df_transposto['Ano'].str.split('.', expand=True)
df_transposto['Tipo'] = df_transposto['Tipo'].map({None : 'Quantidade', '1': 'Valor'})
df_pivot = df_transposto.pivot_table(index=['Id', 'País', 'Ano'], columns='Tipo', values='Valor')
exportação_tratado = df_pivot.reset_index()
exportação_tratado.columns.names = [None]
pais_origem = 'Brasil'
exportação_tratado['Pais_origem'] = pais_origem
exportação_tratado = exportação_tratado[['Ano', 'Pais_origem', 'País', 'Quantidade', 'Valor']]
display(exportação_tratado)
display(exportação_tratado.dtypes)

       Ano Pais_origem         País  Quantidade  Valor
0     1970      Brasil  Afeganistão         0.0    0.0
1     1971      Brasil  Afeganistão         0.0    0.0
2     1972      Brasil  Afeganistão         0.0    0.0
3     1973      Brasil  Afeganistão         0.0    0.0
4     1974      Brasil  Afeganistão         0.0    0.0
...    ...         ...          ...         ...    ...
7393  2019      Brasil       Vietnã        20.0   32.0
7394  2020      Brasil       Vietnã        86.0  584.0
7395  2021      Brasil       Vietnã         0.0    0.0
7396  2022      Brasil       Vietnã       130.0  277.0
7397  2023      Brasil       Vietnã        72.0  128.0

[7398 rows x 5 columns]

Ano             object
Pais_origem     object
País            object
Quantidade     float64
Valor          float64
dtype: object